---
linters-settings:
  exhaustive:
    default-signifies-exhaustive: true

  gci:
    sections:
      - standard
      - default
      - prefix(github.com/cerbos/protoc-gen-jsonschema)

  gofumpt:
    extra-rules: true

  govet:
    enable-all: true
    disable:
      - shadow

  nolintlint:
    allow-unused: false
    require-specific: true

  tagliatelle:
    case:
      rules:
        json: goCamel
        yaml: goCamel
        xml: goCamel
        bson: goCamel

linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - gci
    - goconst
    - gocritic
    - godot
    - gofumpt
    - goimports
    - gomoddirectives
    - gosec
    - govet
    - importas
    - makezero
    - misspell
    - mnd
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tagliatelle
    - tenv
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace
  disable:
    - cyclop
    - depguard
    - dogsled
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocyclo
    - godox
    - gofmt
    - goheader
    - gomodguard
    - goprintffuncname
    - lll
    - nlreturn
    - paralleltest
    - stylecheck
    - testpackage
    - wrapcheck
    - wsl

issues:
  max-same-issues: 30

  exclude-rules:
    - path: _test\.go
      linters:
        - forcetypeassert
        - goconst
        - govet
        - mnd
